### ISSUE TITLE
Add a message that BugDash requires browsers that support importMaps

### ISSUE THREAD

**Issue by theres-waldo** [mozilla/bugdash#14]
**STR**

 1. Run Firefox ESR (currently 102.9.0esr)
 2. Load https://bugdash.moz.tools/

**Expected results**

The site loads.

**Actual results**

The site hangs, showing "Starting BugDash...".

The devtools console shows `Uncaught TypeError: Error resolving module specifier “dialog”. Relative module specifiers must start with “./”, “../” or “/”.`

**Comment by theres-waldo** [comment]
A workaround is to set `dom.importMaps.enabled=true` in `about:config`.

**Comment by globau** [comment]
Thanks for the report.  I'll add a warning to make it clear that importMap support is required.

**Comment by globau** [comment]
note to self:

```
        <script>
            import ("bugdash").catch(() => {
                console.log('no importmap support');
            });
        </script>
```
