### ISSUE TITLE
Bugdash uses a UTF character that's not available (by default) on Ubuntu

### ISSUE THREAD

**Issue by dholbert** [mozilla/bugdash#17]
Bugdash has an arrow icon at the left edge of each section, which renders as UTF missing-character "tofu" on Ubuntu.

(Possibly it becomes visible if you install just the right font, but with the stock set of fonts, it's unavailable.)

Screenshot:
![image](https://github.com/mozilla/bugdash/assets/426803/1db8f3fe-d260-4a6d-81ff-835e52381d08)

This is U+23f5 , i.e. this character:
https://www.compart.com/en/unicode/U+23f5

(It renders as broken "tofu" on this^ page as well.)

Notably that page says `Unicode Version: | 7.0 (June 2014)` -- maybe that means it was introduced too recently (into the standard) for it to reliably available in a font on people's systems?

As one possible alternative, https://www.compart.com/en/unicode/U+25B6 renders just fine for me and was introduced in "Unicode Version:	1.1 (June 1993)".  (It's "Black right-pointing triangle" rather than "Black **medium** right-pointing triangle.")

**Comment by dholbert** [comment]
Code reference:
https://github.com/mozilla/bugdash/blob/34937c1907639c5979b80f9fd4b5154a12fc6767/app/buglist.css#L5C1-L10

(Those `content: ...` lines are what specify this character and its downward-pointing counterpart.  They render with broken boxes for me in the GitHub view of this CSS file, too, since I don't have a font that includes them.)

**Comment by dholbert** [comment]
This isn't browser-specific, BTW -- bugdash also renders with a missing-unicode-character box in Chrome on Ubuntu, as shown here:
![image](https://github.com/mozilla/bugdash/assets/426803/c9d9461f-4616-49ad-9e9c-be129e920b88)

**Comment by globau** [comment]
Thanks, will switch to the symbols from Unicode 1.1 as suggested.

`Unicode Version: | 7.0 (June 2014)`  _sad noise about it being almost 9 years_

**Comment by dholbert** [comment]
Thanks! Verified fixed:
![image](https://github.com/mozilla/bugdash/assets/426803/30022798-960d-4977-85cf-7de4c21f88db)


(And yeah, Unicode 7.0 / 2014 is well into the past at this point. I don't know much about the lifecycles of the various fonts that ship with Ubuntu, so I'm not sure if this symbol missing is an anomaly or an oversight or if it's par-for-the-course.)
