### ISSUE TITLE
Included column sorting in the bugzilla query URLs

### ISSUE THREAD

**Issue by DonalMe** [mozilla/bugdash#18]
When opening a Bugzilla query from Bugdash, it would be useful to list in Bugzilla in the same order as Bugdash.

**Comment by globau** [comment]
This isn't possible in Bugzilla currently; the `order` parameter can either be "whatever the user last used" or "this specific set of columns".

Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1836202
