### ISSUE TITLE
Sort REO Carry Over lists to see not assigned, not recently updated first

### ISSUE THREAD

**Issue by dsmithpadilla** [mozilla/bugdash#20]
For the regression triage board in https://bugdash.moz.tools/#tab.reo, we would like to change the sort order for:
Carry Over Bugs
Carry Over Bugs With NEEDINFO

We would like to sort these by -Oldest Updated, -Not-assigned, Severity

**Comment by globau** [comment]
There's a conflict between the summary (order by assigned then last-modified) and the comment (order by last modified then assigned then severity).

I _think_ you want:

unassigned bugs, ordered by bug creation (oldest first); then assigned bugs, ordered by bug created (oldest first)

I'm not sure how severity fits in here.

With severity perhaps:

unassigned bugs, ordered by severity (s1 first), then by bug creation (oldest first); then assigned bugs, ordered by severity (s1 first), ordered by bug created (oldest first)

or

ordered by severity (s1 first), then by assigned (unassigned first), then by bug creation (oldest first)

for the NEEDINFO list I assume we'd want to replace "bug creation (oldest first)" with "oldest needinfo creation timestamp (oldest first)".

?

**Comment by dsmithpadilla** [comment]
We actually can ignore severity from the initial request. 

We also dont want the oldest bug, we want to see the bug that hasn't been updated in a while.

So it would be unassigned bugs, ordered by recently updated asc
