### ISSUE TITLE
Bugdash favicon looks clipped when viewed with dark theme

### ISSUE THREAD

**Issue by dholbert** [mozilla/bugdash#29]
Here's how the bugdash favicon looks, with a dark Firefox theme (or the default "system theme" choice, with a dark system theme), on a system with standard 100% pixel scaling (not sure about other pixel ratios):
![image](https://github.com/mozilla/bugdash/assets/426803/14bfaa93-b62b-4fe6-b6ea-bd50c91b1734)

The white background-area is awkwardly clipped on the left and top edge. This seems to be because the SVG favicon at https://bugdash.moz.tools/assets/bugdash.svg doesn't have much space at those sides, which rounds to ~zero when viewed at favicon resolution.

Ideally, we should add a bit more of an offset on those sides to make this less of an issue; or, we should provide a dark-theme-friendly favicon (like e.g. github does -- their favicon switches if I change my theme -- though I haven't dug in to see what they're doing to achieve that).

**Comment by globau** [comment]
Here's how it looks with transparency shown as magenta:
![image](https://github.com/mozilla/bugdash/assets/872825/5e698dac-1bde-4ed0-939d-42bedbcf2c56)

This is intended; when the outline isn't clipped I found the bug to be too small to be recognised, and without an outline the magnifying glass isn't visible in dark mode.
