### ISSUE TITLE
Add "Firefox-only WPT failures"

### ISSUE THREAD

**Issue by saschanaz** [mozilla/bugdash#32]
i.e. merge @jgraham's https://jgraham.github.io/wptdash/

Not all WPT failures have corresponding bugs so it would be nice to have a tab for that.

**Comment by globau** [comment]
That dashboard appears to have different goals from bugdash, especially given there isn't always bugs to triage (bugdash is a Bugzilla dashboard focused on triage).

I don't see any compelling reason to integrate wptdash into bugdash.

**Comment by saschanaz** [comment]
That's sad as I think we do need to triage failures or otherwise we just completely miss them while they grow. I'll have my fork for now and see it can convince you.
