### ISSUE TITLE
Add a way to select all components by team name (by URL parameter)

### ISSUE THREAD

**Issue by saschanaz** [mozilla/bugdash#34]
Something like `?team=myteamname` would let us keep one URL instead of having to update URL whenever our list of components changes.

**Comment by globau** [comment]
Deployed, it'll kick in as long as all of the following are true:
- the `Name`/`Team` select field (scope) is set to `Team`
- all selected components are in the same team
- all components in that team are selected

eg. using `DOM LWS` as the team:

1. change scope to `Team`
2. enter `DOM LWS` in the filter field
3. click `Select Visible`

The URL will now be https://bugdash.moz.tools/?team=DOM+LWS
