### ISSUE TITLE
Add the ability to override the default ordering of buglists

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugdash#36]
Joe suggested to have something on the lines of:

```
[ ...document.querySelectorAll('#long-defects .bug-row') ].forEach(node => node.style.display = 'none');
[ ...document.querySelectorAll('#long-defects .bug-row:not(.bug-meta)') ].sort(() => 0.5 - Math.random()).slice(0, 10).forEach(node => node.style.display = 'table-row');
```

(just throw it in the web console when open on long standing defects).

Maybe we can have a button for that somewhere on the title of the three long standing X sections ?

**Comment by globau** [comment]
I'm not clear on the use-case here; can you provide some more details?

A random approach to bug management goes against the grain of the order that bugdash is trying to impose.

**Comment by jensstutte** [comment]
OK, here is what we thought: In order to give people a handle to look into some old bugs when there is some time left during triage, it could be interesting to propose some more or less random set of bugs out of the long standing ones to make it a bit less boring and scary than scrolling through a long list.

I was talking now with my team, also, and they said that this sounds fun, but we might want to have some more criteria for which bugs to pick for that "random cleanup", like excluding:

- Bugs that have already comments from current team members
- Bugs that are part of a meta bug
- Bugs that block some other bug 

I do not think we have yet a 100% clear set of requirements, though, and I also want to check back with Joe.

**Comment by globau** [comment]
Thanks for explaining the reasoning.

I believe I can make this happen in a way that is more consistent bugdash as well as adding generically useful feature.
I'll add the ability to change the sort order of buglists to "Default", "Oldest First", "Newest First", and "Random".

**Comment by jensstutte** [comment]
Another use case for this is to ask some teams to protocol their "success rate" of closing bugs without fix when looking at a random sample of bugs from their backlog. This way we would be able to make better estimations about the percentage of very low hanging fruits in our defects backlog.
