### ISSUE TITLE
Not clear where the hosting requirements come from

### ISSUE THREAD

**Issue by jgraham** [mozilla/bugdash#38]
This part of the README didn't make sense to me:

> While BugDash is a purely client-side static site, due to the storage of Bugzilla API-Keys in localStorage it has to be hosted with a unique origin; this means that github.io or CNAMEs pointing to it are not viable hosting solutions.

From the point of view of the same origin policy subdomains of github.io are unique origins (`github.io` is even on the public suffix list so you don't even have to worry about `document.domain` related edge cases), and origins don't know anything at all about DNS, so the claim that a CNAME pointing to a github hosted domain wouldn't work seems even harder to understand. So I'm not sure there's a real issue here, and if there is I don't understand it based on the description given.

**Comment by globau** [comment]
This was done on advice given to me at the time by someone in security.
If you're looking to self-host, you're welcome to make your own calls on the validity of this statement.

I'll truncate the github.io part of that sentence as it doesn't serve any real purpose.
