### ISSUE TITLE
Add an "Important" component tab with buglists for tracked, S1, S2, and regressions

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugdash#6]
Currently only the triage panel seems to be limited to the selected components (which seems to be wanted looking at the tab design).
It would be good to have this optional also for regressions or tracked bugs, to see at a glance where to put hands.

**Comment by globau** [comment]
Sounds reasonable; morphing summary to reflect the required implementation.

Note to self: rename "Regressions" tab to "Regression Triage".

**Comment by globau** [comment]
This is now live, the Important tab shows, for the selected component(s):
* Blocker (S1) Defects
* Critical (S2) Defects
* 112 (Release) Tracked Bugs
* 113 (Beta) Tracked Bugs
* 114 (Nightly) Tracked Bugs
* 114 (Nightly) New Regressions
* 114 (Nightly) Carry Over Regressions
* 113 (Beta) New Regressions
* 113 (Beta) Carry Over Regressions
* 112 (Release) New Regressions
* 112 (Release) Carry Over Regressions
