### ISSUE TITLE
Bugdash seems to be missing all the bugs for general triage

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/bugdash#7]
Picking up Firefox::General / Toolkit::General triage today, bugdash shows no open bugs except 1 needinfo bug:

But when we use a direct BMO query, like [this one](https://bugzilla.mozilla.org/buglist.cgi?v4=Firefox&o9=substring&f7=OP&f5=CP&f3=product&f12=priority&f2=OP&j8=OR&list_id=16526408&f4=product&f15=CP&f6=CP&v3=Toolkit&f11=OP&o13=casesubstring&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&v12=--&f14=CP&v9=General&o4=casesubstring&f13=bug_severity&f1=OP&j2=OR&f8=OP&query_format=advanced&o3=substring&f9=component&j11=OR&o12=casesubstring&v13=--&f10=CP), there seem to be many untriaged bugs.

I'm not sure what query is used by bugdash behind the scenes, but this seemed worth reporting. Thanks!

**Comment by globau** [comment]
There's quite a few things wrong with that query:
* it's showing bugs where _either_ the priority or severity is missing.  Bugdash follows [our triage process](https://firefox-source-docs.mozilla.org/bug-mgmt/policies/triage-bugzilla.html) that requires just the severity to be set
* the component selection is weirdly constructed resulting, with the end result of the product being ignored and lists bugs from any component that contain "General" (you'll note that bugs from `Firefox Build System :: General: Unsupported` are present)
* it's listing bugs of any type - defect, enhancement, and task, as well as meta bugs; our triage process only requires severities to be set on defects

You can see the query that BugDash uses [here](https://bugzilla.mozilla.org/query.cgi?email1=wptsync%40mozilla.bugs&emailreporter1=1&emailtype1=notequals&f1=bug_type&f10=CP&f2=flagtypes.name&f3=bug_severity&f4=keywords&f5=OP&f6=OP&f7=product&f8=component&f9=CP&include_fields=assigned_to%2Ccomponent%2Ccreation_time%2Ccreator%2Cflags%2Cgroups%2Cid%2Ckeywords%2Clast_change_time%2Cpriority%2Cproduct%2Cseverity%2Csummary%2Ctriage_owner%2Ctype&j5=OR&keywords=intermittent_failure&keywords_type=nowords&limit=0&list_id=16526841&o1=equals&o2=notsubstring&o3=anyexact&o4=notsubstring&o7=equals&o8=equals&query_format=advanced&resolution=---&v1=defect&v2=needinfo&v3=--%2C%20n%2Fa&v4=meta&v7=Toolkit&v8=General).
