### ISSUE TITLE
Triage queries should not exclude geckoview products

### ISSUE THREAD

**Issue by dsmithpadilla** [mozilla/bugdash#8]
https://bugdash.moz.tools/#tab.reo queries do not include tickets where the Product is Geckoview. (For example https://bugzilla.mozilla.org/show_bug.cgi?id=1827583)

Old query example : https://mzl.la/3AU63xZ

We should remove that condition and display these tickets.

**Comment by globau** [comment]
This was fixed earlier today in 4c5d41140780b49f27f2546a81a923f10bfcc169
