### ISSUE TITLE
Stop excluding bugs with NEEDINFO on the S1/S2 "Important" lists

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugdash#9]
The tab added in #6 is very helpful, thanks!

I just wondered if we should ignore bugs with a pending needinfo in some or all of these queries. In this more fine grained use case I would want to see for example all S2 bugs (as we have an OKR towards them and knowing that some ni? tend to stay active for a while). At least for the S1/S2 lists that would apply, IMHO.

**Comment by globau** [comment]
Sorry, not sure what the exact ask is here.

Currently S1/S2 are excluding bugs with NEEDINFOs - I _think_ you're asking for the NEEDINFO exclusion to be removed from these?

The three "Tracked Bugs" lists are not excluding NEEDINFOs; this feels right as there tends to be few bugs that are NEEDINFO heavy.

The six "Regressions" lists are excluding NEEDINFOs, but as they are mirrors of the "Regression Triage" lists (ie. REO) they should remain filtered.

**Comment by jensstutte** [comment]
> Sorry, not sure what the exact ask is here.
> 
> Currently S1/S2 are excluding bugs with NEEDINFOs - I _think_ you're asking for the NEEDINFO exclusion to be removed from these?

Yes, these were the reason I filed this issue, sorry if that was not clear. These queries mostly fit the use case "where do I stand with my team for the S2 OKR?" and it is confusing to see diverging numbers from what I already have in mind as baseline.
 
> The three "Tracked Bugs" lists are not excluding NEEDINFOs; this feels right as there tends to be few bugs that are NEEDINFO heavy.

Correct, please leave them as is.
 
> The six "Regressions" lists are excluding NEEDINFOs, but as they are mirrors of the "Regression Triage" lists (ie. REO) they should remain filtered.

I have a less strong opinion here. I think the use case for this filtered list is mostly "where do I need to nag someone next as a team manager" and excluding the ones with ni? seems slightly dangerous (there are some really long-living ni? sometimes). On the other hand I'd rather want to get people to answer ni? always fast, anyways. But for the time being I'd probably prefer to err on having more than less bugs listed here. We could maybe show if there is a pending ni? in the list?

**Comment by globau** [comment]
> Yes, these were the reason I filed this issue, sorry if that was not clear. These queries mostly fit the use case "where do I stand with my team for the S2 OKR?" and it is confusing to see diverging numbers from what I already have in mind as baseline.

👍🏻  I'll drop the NEEDINFO filter and add an indicator if there's an open NI request.

> I have a less strong opinion here.

OK, lets leave it as-is.

Addressing NI responsiveness is out of scope of this dashboard, but IMHO something worth putting effort into.
